name: 02 - Workflow Events

on: 
  push:
  pull:
  schedule:
    - cron: '*/5 * * * *' # Every day at midnight UTC
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "This workflow was triggered by ${{github.event_name}} event!"